import { Fragment, type ReactNode } from "react";

import type { Metadata } from "next";
import { redirect } from "next/navigation";

import { createClient } from "@/lib/supabase/server";

import { AppHeader } from "@/components/elements/app-header";

export const metadata: Metadata = {
  title: "Welcome back! | MotionMetrics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const supabase = createClient();

  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/login");
  }

  return (
    <Fragment>
      <div className="rounded-xl pb-8 border-4 border-dark-200 bg-dark-50 h-[calc(100dvh_-_68px)] overflow-hidden overflow-y-auto">
        {children}
      </div>

      <AppHeader />
    </Fragment>
  );
}
