import { Fragment, type ReactNode } from "react";

import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";

import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "Welcome back! | MotionMetrics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const supabase = createClient();

  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/login");
  }

  return (
    <Fragment>
      <div className="rounded-xl border-4 border-dark-200 bg-dark-50 h-[calc(100dvh_-_68px)] overflow-hidden overflow-y-auto">
        {children}
      </div>

      <header className="fixed bottom-0 left-0 right-0">
        <menu className="flex items-center justify-between px-8 py-5 w-full h-full">
          <li>
            <Link href="#">Home</Link>
          </li>
          <li>
            <Link href="#">Workouts</Link>
          </li>
          <li>
            <Link href="#">Profile</Link>
          </li>
        </menu>
      </header>
    </Fragment>
  );
}
