import type { ReactNode } from "react";

import type { Metadata } from "next";

import "./globals.css";

import { body } from "@/lib/fonts/index";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Home | MotionMetrics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative min-h-screen bg-light-100 font-body text-light-900 antialiased",
          body.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
