import type { ReactNode } from "react";

import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

import { body } from "@/lib/fonts/index";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Home | MotionMetrics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-[100dvh] bg-dark-200  font-body text-[#FBF8F1] antialiased§",
          body.variable,
        )}
      >
        <div className="rounded-b-xl px-3 border-4 border-dark-200 bg-dark-50 h-[calc(100dvh_-_68px)] overflow-hidden overflow-y-auto">
          {children}
        </div>

        <header className="fixed bottom-0 left-0 right-0">
          <menu className="flex items-center justify-between px-8 py-5 w-full h-full">
            <li>
              <Link href="#">Home</Link>
            </li>
            <li>
              <Link href="#">Workouts</Link>
            </li>
            <li>
              <Link href="#">Profile</Link>
            </li>
          </menu>
        </header>
      </body>
    </html>
  );
}
